workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS deployment target
        script: |
          # Update minimum iOS version in Podfile
          echo "Updating iOS deployment target..."
          sed -i '' 's/# platform :ios.*/platform :ios, "12.0"/' ios/Podfile
          
      - name: Flutter setup and build
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
          # Specify the minimum iOS version
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
