workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: 14.3
    scripts:
      - name: Flutter setup and build with custom build settings
        script: |
          # Clean and setup
          flutter clean
          flutter pub get
          
          # Create iOS setup
          flutter create . --platforms=ios
          
          # Directly modify build settings before pod install
          echo "platform :ios, '12.0'" > ios/Podfile.new
          cat ios/Podfile >> ios/Podfile.new
          mv ios/Podfile.new ios/Podfile
          
          # Set min iOS version in all relevant files
          cd ios
          
          # Force specific compiler flags for all targets
          echo "IPHONEOS_DEPLOYMENT_TARGET = 12.0" > exportOptions.plist
          
          # Set min iOS version for all pod targets
          echo "post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
            end
          end" >> Podfile
          
          # Install pods with explicit settings
          pod install
          cd ..
          
          # Build with explicit iOS version
          IPHONEOS_DEPLOYMENT_TARGET=12.0 flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
