workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter setup and build
        script: |
          # Clean and setup
          flutter clean
          flutter pub get
          
          # Create iOS setup first
          flutter create . --platforms=ios
          
          # Now we can modify the Podfile since it exists
          echo "platform :ios, '12.0'" >> ios/Podfile
          
          # Install pods and build
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
