workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter setup and build
        script: |
          flutter clean
          flutter pub get
          # Create complete iOS setup on the Mac
          flutter create . --platforms=ios
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
