name: tafseer
description: An Islamic learning application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^1.2.2
  dart_openai: ^5.1.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.2
  google_fonts: ^6.2.1
  win32: ^5.10.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  cloud_functions: ^5.3.4
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_performance: ^0.10.1+4
  firebase_auth: ^5.5.1
  path: ^1.9.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.11
  firebase_remote_config: ^5.4.2
  font_awesome_flutter: ^10.6.0
  device_preview: ^1.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  flutter_markdown: ^0.6.15
  hijri: ^3.0.0
  flutter_compass: ^0.8.1
  timezone: ^0.9.2
  awesome_notifications: ^0.10.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/data/
    - .env
    - assets/data/faq_data.json
    - assets/data/translation.json
    - assets/data/nawawi.json
    - assets/data/quran-arabic.json
    - assets/icon/compass_needle.png
    - assets/icon/compass_needle.svg
  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true  
  image_path: "assets/icon/icon.png"
