name: tafseer
description: An Islamic learning application

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^1.2.2
  dart_openai: ^5.1.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.2
  google_fonts: ^6.2.1
  win32: ^5.10.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.1
  cloud_functions: ^4.6.0
  firebase_analytics: ^10.8.10
  firebase_crashlytics: ^3.4.1
  firebase_performance: ^0.9.3+8
  firebase_auth: ^4.20.0
  path: 1.9.1  
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  location: ^7.0.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.0
  firebase_remote_config: ^4.3.8
  font_awesome_flutter: ^10.6.0
  hijri:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/data/
    - .env
    - assets/data/faq_data.json
    - assets/data/translation.json
    - assets/data/nawawi.json

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
