// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpkMWl67wdTVmsDBExNyebPaugh0C4w0',
    appId: '1:121009374788:web:4a7b21d172a333709fde11',
    messagingSenderId: '121009374788',
    projectId: 'tafseer-7f736',
    authDomain: 'tafseer-7f736.firebaseapp.com',
    storageBucket: 'tafseer-7f736.firebasestorage.app',
    measurementId: 'G-KGQMWMX2CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtHlzJzarhKNVWL5GscUWbse9Es7dBtGg',
    appId: '1:121009374788:android:74667ccad0ff8c509fde11',
    messagingSenderId: '121009374788',
    projectId: 'tafseer-7f736',
    storageBucket: 'tafseer-7f736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgRWDBVfOeRaVMyj-BklFqDtCMb3xsmg',
    appId: '1:121009374788:ios:4d5d6581aec70f959fde11',
    messagingSenderId: '121009374788',
    projectId: 'tafseer-7f736',
    storageBucket: 'tafseer-7f736.firebasestorage.app',
    iosBundleId: 'com.example.islam101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgRWDBVfOeRaVMyj-BklFqDtCMb3xsmg',
    appId: '1:121009374788:ios:4d5d6581aec70f959fde11',
    messagingSenderId: '121009374788',
    projectId: 'tafseer-7f736',
    storageBucket: 'tafseer-7f736.firebasestorage.app',
    iosBundleId: 'com.example.islam101',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPpkMWl67wdTVmsDBExNyebPaugh0C4w0',
    appId: '1:121009374788:web:cd2d6669512bcf029fde11',
    messagingSenderId: '121009374788',
    projectId: 'tafseer-7f736',
    authDomain: 'tafseer-7f736.firebaseapp.com',
    storageBucket: 'tafseer-7f736.firebasestorage.app',
    measurementId: 'G-D4DM4W6PR4',
  );
}
