platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  # Add other Firebase pods your app needs
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
